### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by maxwell652** [Synwit-Co-Ltd/DAPLink#1]
你好，我在编译时出现以下错误，请问是哪里的配置有误呢？
![image](https://github.com/Synwit-Co-Ltd/DAPLink/assets/23316609/55ac2cef-3718-407f-aa70-7402e9f81040)

**Comment by XIVN1987** [comment]
是不是你的Keil版本太旧了？？我用的 5.36

**Comment by maxwell652** [comment]
> 是不是你的Keil版本太旧了？？我用的 5.36

嗯，可能是版本原因，我换5.31的编译是没有问题的。另外想咨询一下，SWXT-QFP100-341VEA2这款开发板，在用cmsis-dap下载器连接时找不到芯片，会有哪些原因呢

**Comment by XIVN1987** [comment]
第一步、首先用 Jlink 验证下载没问题，，这样可以确保板子、芯片、连接没问题
第二步、用你的 CMSIS-DAP 验证给其他芯片下载没问题，，这样可以验证 CMSIS-DAP 正常
第三步、Keil 中调试器要选 CMSIS-DAP ARMv8-M Debugger，，因为 SWM341 是 Cortex-M33 内核

**Comment by XIVN1987** [comment]
Cortex-M33 内核是 ARMv8 架构

**Comment by maxwell652** [comment]
> 第一步、首先用 Jlink 验证下载没问题，，这样可以确保板子、芯片、连接没问题 第二步、用你的 CMSIS-DAP 验证给其他芯片下载没问题，，这样可以验证 CMSIS-DAP 正常 第三步、Keil 中调试器要选 CMSIS-DAP ARMv8-M Debugger，，因为 SWM341 是 Cortex-M33 内核

JLink和CMSIS-DAP都没法下载，同时这两个下载器给其他芯片下载都是没有问题的。
用cmsis-dap连接swm341时，识别为unknown device
![image](https://github.com/Synwit-Co-Ltd/DAPLink/assets/23316609/e73f28eb-3080-4040-be86-6854676c5ee9)

**Comment by XIVN1987** [comment]
1、检查下物理连线，，调试器和板子连线尽量短
2、用ISP把341芯片擦除一下

**Comment by maxwell652** [comment]
可能还是keil版本问题，换更高版本就可以找到芯片了。
[另外，编译报错这个问题，arm官方也有相应的解释，按照他们提供的方法，可以用低版本的keil进行编译了[](url)](https://developer.arm.com/documentation/ka004410/latest)
